apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: python-app
  description: Python app that displays time.
  annotations:
    github.com/project-slug: MrpPolo/python-app
    backstage.io/techdocs-ref: dir:.
spec:
  type: service
  owner: team-a
  lifecycle: experimental